### ISSUE TITLE
How to manage groups and subgroups?

### ISSUE THREAD

**Issue by remioukrat** [lawmurray/doxide#43]
I have the following yaml file
```yaml
groups:
  - name: A
    title: A api
    description: A part
    groups:
      - name: B
         title: B api
         description: B part
         groups:
           - name: C
              title: C api
              description: C part
```

and in a class of the C subsubgroup I have written 
```c++
/**
 * @ingroup A B C
 */
```

But the documentation is generated in the A group page and not in the C sub sub group page.

Please, how can I manage hierarchy with accuracy?
